---
- name: Install nginx, start it, and deploy webpage
  hosts: servers
  become: yes
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: latest

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html to Nginx default root
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
